word_list = [
    "ability", "absolute", "acceptance", "accomplish", "achievement", "adventure", "affection", "agreement", "ambition", "appreciation",
    "balance", "beautiful", "beginning", "benevolent", "blissful", "bravery", "brightness", "calmness", "celebration", "challenge",
    "charismatic", "cheerfulness", "clarity", "comfort", "commitment", "compassion", "confidence", "connection", "consciousness", "courage",
    "creativity", "curiosity", "dedication", "delightful", "dependable", "determination", "diversity", "dreams", "dynamic", "efficiency",
    "elegance", "embrace", "empathy", "empowerment", "energy", "enthusiasm", "equality", "excellence", "experience", "exploration",
    "faithfulness", "fascination", "flexibility", "freedom", "fulfillment", "generosity", "gracefulness", "gratitude", "happiness", "harmony",
    "healing", "honesty", "hopeful", "humility", "imagination", "immortality", "improvement", "independence", "innovation", "inspiration",
    "integrity", "intuition", "joyfulness", "kindness", "knowledge", "laughter", "liberation", "lightness", "love", "magic",
    "magnificence", "mindfulness", "motivation", "nurturing", "open-minded", "optimism", "passion", "patience", "peacefulness", "perfection",
    "perseverance", "playfulness", "positivity", "powerful", "presence", "prosperity", "purpose", "quality", "radiance", "reassurance",
    "reflection", "rejuvenation", "reliability", "resilience", "respect", "revolutionary", "satisfaction", "self-love", "serenity", "simplicity",
    "spontaneity", "strength", "success", "sustainability", "tenacity", "tranquility", "transcendence", "trust", "unconditional", "understanding",
    "unity", "vibrancy", "victory", "vitality", "warmth", "wholeness", "wonder", "xanadu", "xenial", "xerox", "youthfulness",
    "zeal", "zenith", "zest", "abundance", "adventure", "authenticity", "blossoming", "captivating", "dazzling", "effervescent",
    "flourishing", "graceful", "harmonious", "inspirational", "jubilant", "kaleidoscopic", "luminous", "mesmerizing", "nourishing", "optimistic",
    "passionate", "quintessential", "resplendent", "serendipitous", "transformative", "unforgettable", "vivacious", "whimsical", "x-factor", "yielding",
    "zephyr", "abracadabra", "bewitching", "cynosure", "desire", "elan", "felicity", "glamorous", "halcyon", "illumination",
    "jocund", "kismet", "laudable", "mellifluous", "nurturing", "opulent", "peregrinate", "quiescent", "rhapsody", "seraphic",
    "triumphant", "ubiquitous", "voluptuous", "winsome", "xenodochial", "yaraana", "zen", "aplomb", "bucolic", "comely",
    "diaphanous", "effulgent", "farrago", "gossamer", "halo", "imbrication", "kaleidoscopic", "lugubrious",
    "magniloquent", "nonchalant", "obfuscate", "plethora", "quixotic", "rampant", "serpentine", "talisman", "ubiquity", "verisimilitude",
    "winsome", "xylophone", "yarn", "zeitgeist"
]
